### ISSUE TITLE
some picture

### ISSUE THREAD

**Issue by snping** [rishabh1b/TrafficSignRecognition#4]
HELLO, thank you your code.
I can't run the code when I use my picture. 
error find_mser (line 12)
[r,~] = vl_mser(im_roi,'MinDiversity',0.7,...

error tsr_red_sign (line 42)
    M = find_mser(im_roi, delta, maxarea, minarea, size(im_r));
could you help me ?

**Comment by rishabh1b** [comment]
Sorry for my delayed response. It seems I was not notified about this issue.
Your problem is that you are not using the vl_feat library. I have mentioned about this in readme. I am using find_mser function from their library for finding MSER regions. Get it from here - http://www.vlfeat.org/install-matlab.html
Also, I have migrated all my perception repositories using MATLAB here  - https://github.com/rishabh1b/RoboticsPerception

**Comment by rishabh1b** [comment]
Also, I am updating the readme here with a .gif
